# Generated by Django 5.0.6 on 2024-06-18 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0004_conjugation_unique_word_tense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=100)),
                ('tagalog', models.CharField(max_length=100)),
                ('is_question', models.BooleanField(blank=True, default=False)),
                ('audio_url', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhraseWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_conjugated', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('conjugation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.conjugation')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_words', to='phrases.phrase')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='phraseword',
            constraint=models.UniqueConstraint(fields=('phrase', 'word', 'order'), name='unique_phrase_word_order'),
        ),
    ]
