# Generated by Django 5.0.6 on 2024-06-23 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phraseword',
            name='is_conjugated',
        ),
    ]
