# Generated by Django 5.0.6 on 2024-06-23 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0002_remove_phraseword_is_conjugated'),
        ('words', '0013_alter_conjugation_accents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phraseword',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.word'),
        ),
    ]
