# Generated by Django 5.0.6 on 2024-06-11 06:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=35)),
                ('tagalog', models.CharField(max_length=35)),
                ('root', models.CharField(max_length=35)),
                ('accents', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('audio_url', models.URLField(default='<django.db.models.fields.CharField>.mp3', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conjugation',
            fields=[
                ('wordbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='words.wordbase')),
            ],
            bases=('words.wordbase',),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('wordbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='words.wordbase')),
                ('part_of_speech', models.CharField(choices=[('N', 'noun'), ('V', 'verb'), ('ADJ', 'adjective'), ('ADV', 'adverb'), ('PRON', 'pronoun'), ('PREP', 'preposition'), ('CONJ', 'conjunction'), ('INTERJ', 'interjection'), ('INTERROG', 'interrogative'), ('ART', 'article'), ('PART', 'particle')], max_length=14)),
            ],
            bases=('words.wordbase',),
        ),
    ]
