# Generated by Django 5.0.6 on 2024-06-16 00:34

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=35), size=None)),
                ('tagalog', models.CharField(max_length=35)),
                ('root', models.CharField(max_length=35)),
                ('accents', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('audio_url', models.URLField(unique=True)),
                ('part_of_speech', models.CharField(choices=[('N', 'noun'), ('V', 'verb'), ('ADJ', 'adjective'), ('ADV', 'adverb'), ('PRON', 'pronoun'), ('PREP', 'preposition'), ('CONJ', 'conjunction'), ('INTERJ', 'interjection'), ('INTERROG', 'interrogative'), ('ART', 'article'), ('PART', 'particle')], max_length=14)),
                ('is_irregular_verb', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Conjugation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tense', models.CharField(choices=[('PAST', 'past'), ('PRES', 'present'), ('FUT', 'future')], max_length=7)),
                ('english', models.CharField(max_length=35)),
                ('tagalog', models.CharField(max_length=35)),
                ('audio_url', models.URLField(unique=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjugations', to='words.word')),
            ],
        ),
    ]
