# Generated by Django 5.0.6 on 2024-06-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_conjugation_audio_url'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conjugation',
            constraint=models.UniqueConstraint(fields=('word', 'tense'), name='unique_word_tense'),
        ),
    ]
