# Generated by Django 5.0.6 on 2024-06-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_conjugation_unique_word_tense'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='note',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
