# Generated by Django 5.0.6 on 2024-06-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_alter_word_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='is_irregular_verb',
            field=models.BooleanField(blank=True),
        ),
    ]
