# Generated by Django 5.0.6 on 2024-06-22 00:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_alter_word_is_irregular_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjugation',
            name='accents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
