# Generated by Django 5.0.6 on 2024-06-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_conjugation_accents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='audio_url',
            field=models.CharField(blank=True, max_length=45, unique=True),
        ),
    ]
