# Generated by Django 5.0.6 on 2024-06-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_alter_word_audio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='is_irregular_verb',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
