# Generated by Django 5.0.6 on 2024-06-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_alter_word_is_irregular_verb'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('tagalog', 'accents'), name='unique_tagalog_accents'),
        ),
    ]
