# Generated by Django 5.0.6 on 2024-06-22 03:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_word_unique_tagalog_accents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjugation',
            name='audio_url',
            field=models.CharField(blank=True, max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='accents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
