# Generated by Django 5.0.6 on 2024-06-22 03:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0012_alter_conjugation_audio_url_alter_word_accents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjugation',
            name='accents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
